# Generated by Django 2.0.7 on 2018-12-10 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehourelectricity',
            name='kilo_watt',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='panel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='panel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
        migrations.AlterField(
            model_name='panel',
            name='serial',
            field=models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterUniqueTogether(
            name='panel',
            unique_together={('brand', 'serial')},
        ),
    ]
